### ISSUE TITLE
Figure out which version of sensu-go to pin

### ISSUE THREAD

**Issue by ccressent** [sensu-community/sensu-plugin-sdk#19]
Right now `go.mod` pins some random commit from May 2019. It should probably reference a `sensu-go` release?

**Comment by echlebek** [comment]
It now pins 5.17.1 as of my latest merge.

**Comment by ccressent** [comment]
Thanks, that's better!

But now my question is: how do we deal with the fact that as a user of the SDK, I might want to target a different version of `sensu-go` than the latest release?

**Comment by echlebek** [comment]
I feel like the SDK should only really be using the core/v2 API from sensu-go. And we therefore likely only want the latest release.

**Comment by jspaleta** [comment]
I think we've got this solved in the latest releases.   
go.mod now lists
github.com/sensu/sensu-go/api/core/v2 v2.0.0
github.com/sensu/sensu-go/types v0.1.0

I'm closing this as resolved.
