### ISSUE TITLE
Support Sensu Go License Validation

### ISSUE THREAD

**Issue by portertech** [sensu-community/sensu-plugin-sdk#33]
Extract Sensu Go license validation logic from the commercial distribution of Sensu and place it in a new project repository, sensu/sensu-licensing. Update the SDK to import the licensing project and support optional license enforcement for Handlers. Update the commercial distribution of Sensu to import and use the licensing project. Handler plugin authors can then choose to require a valid license for plugin execution or partial functionality (good signature and valid until timestamp). The commercial distribution of Sensu Go will soon expose a cluster's active license file to handler plugins via an environment variable, `SENSU_LICENSE_FILE`. The license file is JSON encoded. This work will result in a new release of the SDK.

Proposal document: https://docs.google.com/document/d/1tHKIyx7kCetxwfpWfjUUlJCK9cpOiNrk2NWGgwLw8rQ/edit#

**Comment by jspaleta** [comment]
Can we get that SENSU_LICENSE_FILE exported in sensuctl env as well?  Would really help with dev/testing.

**Comment by nikkictl** [comment]
@jspaleta could you [file an issue to sensu-go](https://github.com/sensu/sensu-go/issues/new/choose) for that work in `sensuctl env`?

**Comment by nikkictl** [comment]
@sensu-community/engineering I created [sensu/sensu-licensing](https://github.com/sensu/sensu-licensing) as part of this effort, migrating everything from [sensu/sensu-enterprise-go/api/licensing/v2](https://github.com/sensu/sensu-enterprise-go/tree/v5.20.2/api/licensing/v2) (and a few other scripts/files) over in the same directory structure. It is currently a private repo (to ensure I have not leaked any code we don't want public), but I would like to make it public so I can tag it and use the v2 module in sensu-enterprise-go. If you could take a quick look and give a 👍to flip the bit, that would be great!

**Comment by nikkictl** [comment]
[sensu/sensu-licensing](https://github.com/sensu/sensu-licensing) has now been made public with the first module release [v0.1.0](https://github.com/sensu/sensu-licensing/releases/tag/v0.1.0)! The SDK can now use the license file validation function.

**Comment by calebhailey** [comment]
🙌
